Fix bug in JSON serialization when parsing array types
Thanks to our `nom_jsonpp` example, we caught a bug in the serialization of an array value within an object when trying to parse the `inventory.json` test file at `Resources/tests/serializers/json/inventory.json`.

```shell
build/debug-dyn/bin/nom_jsonpp build/debug-dyn/bin/inventory.json
ERROR: Could not serialize values; an array cannot exist within another array.
INFO: Stubbed function bool nom::JsonCppSerializer::write_object(const Value &, Json::Value &) const was called
ERROR: Could not serialize values; invalid object?
ERROR: Could not serialize the source object.
```